Support Linux_arm64 distribution scripts

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -151,12 +151,12 @@ runs:
             pkgs=(glibc-static)
             case "${{ env.INPUTDISTSCRIPT }}" in
               dist-Linux_x86_64.u) ;;
-              dist-Linux_aarch64.u) ;;
+              dist-Linux_arm64.u) ;;
               dist-Linux_armv7.u) ;;
               dist-Linux_x86.u)
                 pkgs+=(glibc-static.i686 glibc-devel.i686 libgcc.i686 libstdc++.i686 gcc-toolset-14-libstdc++-devel.i686)
                 ;;
-              *) echo "::error title=⛔ error hint::Unsupported distribution script '${{ env.INPUTDISTSCRIPT }}' for Linux. Supported Linux distribution scripts: dist-Linux_x86_64.u, dist-Linux_aarch64.u, dist-Linux_armv7.u, dist-Linux_x86.u"; exit 1 ;;
+              *) echo "::error title=⛔ error hint::Unsupported distribution script '${{ env.INPUTDISTSCRIPT }}' for Linux. Supported Linux distribution scripts: dist-Linux_x86_64.u, dist-Linux_arm64.u, dist-Linux_armv7.u, dist-Linux_x86.u"; exit 1 ;;
             esac
             dnf install -y "${pkgs[@]}"
           fi
