Move Document Import after successful distribute steps

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -135,35 +135,6 @@ runs:
           echo "::error title=⛔ error hint::Distribution keypair missing. You need to populate 'distribute_${{ steps.dk-vars.outputs.dk_id_version_majminunder }}_pubkey' and 'distribute_${{ steps.dk-vars.outputs.dk_id_version_majminunder }}_seckey' in the Secrets for your workflow. See more in https://docs.github.com/en/actions/security-guides/encrypted-secrets. Then set the 'pubkey' and 'seckey' inputs in the 'with:' block of the workflow step, like the following on two lines: ${{ format('pubkey: {0}{1}{1} secrets.distribute_{3}_pubkey {2}{2} seckey: {0}{1}{1} secrets.distribute_{3}_seckey {2}{2}', '\$', '{', '}', steps.dk-vars.outputs.dk_id_version_majminunder) }}"
           exit 1
 
-      - name: Document Import Command
-        shell: bash
-        run: |
-          PROJECTDIR='${{ github.workspace }}'
-
-          # parse options
-          tag='${{ github.ref_name }}'
-          repository='${{ github.repository }}'
-          capture() {
-            printf "%s\n" "$@" >> "$GITHUB_STEP_SUMMARY"
-            printf "%s\n" "$@" >> '${{ github.workspace }}-CHANGELOG.txt'
-          }
-          if [ -z "$repository" ]; then
-            echo "Error: repository is required" >&2
-            usage
-          fi
-          if [ -z "$tag" ]; then
-            echo "Error: tag is required" >&2
-            usage
-          fi
-
-          capture "### Importing this package"
-          capture ''
-          capture '```'
-
-          printf "./dk0 add github-l2 %s@%s\n" "$repository" "$tag"
-          capture "./dk0 add github-l2 ${repository}@${tag}"
-          capture '```'
-
       # --------- C.1: Get dksrc/dk0 ----------
 
       - name: Get dksrc/dk0
@@ -330,6 +301,35 @@ runs:
           if ($LASTEXITCODE -ne 0) {
             throw "dk0 query failed with exit code $LASTEXITCODE"
           }
+
+      - name: Document Import Command
+        shell: bash
+        run: |
+          PROJECTDIR='${{ github.workspace }}'
+
+          # parse options
+          tag='${{ github.ref_name }}'
+          repository='${{ github.repository }}'
+          capture() {
+            printf "%s\n" "$@" >> "$GITHUB_STEP_SUMMARY"
+            printf "%s\n" "$@" >> '${{ github.workspace }}-CHANGELOG.txt'
+          }
+          if [ -z "$repository" ]; then
+            echo "Error: repository is required" >&2
+            usage
+          fi
+          if [ -z "$tag" ]; then
+            echo "Error: tag is required" >&2
+            usage
+          fi
+
+          capture "### Importing this package"
+          capture ''
+          capture '```'
+
+          printf "./dk0 add github-l2 %s@%s\n" "$repository" "$tag"
+          capture "./dk0 add github-l2 ${repository}@${tag}"
+          capture '```'
 
       - name: Save logs
         if: always()
